server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 5432
    driver-class-name: org.postgresql.Driver

upload:
  folder: /D:/Java/spring-boot/src/main/resources/static/file
